In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
from sklearn.neighbors import KNeighborsClassifier
from scipy.spatial.distance import mahalanobis
from sklearn.svm import SVC
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import pairwise_distances
from sklearn.linear_model import LogisticRegression
from mpl_toolkits.mplot3d import Axes3D

In [13]:
train=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")
val=pd.read_csv("val.csv")
train.drop(columns=["Unnamed: 0"],inplace=True)
test.drop(columns=["Unnamed: 0"],inplace=True)
val.drop(columns=["Unnamed: 0"],inplace=True)

In [14]:
scaler = StandardScaler()
x_train=train.drop(columns=["species"])
y_train=train["species"]

x_test=test.drop(columns=["species"])
y_test=test["species"]

x_val=val.drop(columns=["species"])
y_val=val["species"]

x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_val=scaler.transform(x_val)

In [15]:
log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)
y_test_pred = log_reg.predict(x_test)  
conf_matrix = confusion_matrix(y_test, y_test_pred)
accuracy = accuracy_score(y_test, y_test_pred)
precision = precision_score(y_test, y_test_pred, average='macro', zero_division=1)
recall = recall_score(y_test, y_test_pred, average='macro', zero_division=1)
print("the results on test data")
print("Confusion Matrix:\n", conf_matrix)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

the results on test data
Confusion Matrix:
 [[96  0  0  0  0  0  0  0  0]
 [ 0 83  0  0  0  0  0  0  0]
 [ 0  0 53  0  0  0  0 40  0]
 [ 0  0  0 87  0  0  0  0  0]
 [ 0  0  0  0 95  0  0  0  0]
 [ 0  0  0  0  1 91  0  0  0]
 [ 0  0  0  0  0  0 83  0  0]
 [ 0  0 16  0  0  0  0 80  0]
 [ 0  0  0  0  0  0  0  0 91]]
Accuracy: 0.9301470588235294
Precision: 0.9360406602254427
Recall: 0.9324840268038024
