In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

df = pd.read_csv("7.csv") 

X = df.drop("species", axis=1)
y = df["species"]

X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.111, random_state=42, stratify=y_train_val)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

model = LogisticRegression(max_iter=1000, multi_class='multinomial', solver='lbfgs', random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred) * 100)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 93.38235294117648

Classification Report:
                        precision    recall  f1-score   support

    Anabas testudineus       1.00      1.00      1.00        48
     Coilia dussumieri       1.00      1.00      1.00        41
Otolithoides biauritus       0.78      0.60      0.67        47
     Otolithoides pama       1.00      1.00      1.00        43
     Pethia conchonius       1.00      1.00      1.00        48
  Polynemus paradiseus       1.00      1.00      1.00        46
  Puntius lateristriga       1.00      1.00      1.00        42
        Setipinna taty       0.68      0.83      0.75        48
 Sillaginopsis panijus       1.00      1.00      1.00        45

              accuracy                           0.93       408
             macro avg       0.94      0.94      0.94       408
          weighted avg       0.94      0.93      0.93       408

Confusion Matrix:
[[48  0  0  0  0  0  0  0  0]
 [ 0 41  0  0  0  0  0  0  0]
 [ 0  0 28  0  0  0  0 19  0]
 [ 0 

/home/kali/Desktop/Artificial_Intelligence/venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
